services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: frontend/build
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    branch: main

  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    autoDeploy: true
    branch: main
